### ISSUE TITLE
Height of Microcart in mobile

### ISSUE THREAD

**Issue by AishwaryShrivastav** [vuestorefront/vsf-capybara#576]
## Current behavior

Micor cart hieght is bit short 

## Expected behavior

We can remove micro cart height as back button is already there 

## Steps to reproduce the issue

Add any product to cart and click the cart icon, on mobile device

## Can you handle fixing this bug by yourself?

- [X] YES
- [ ] NO

## Environment details

- Browser:  All
- OS:  All
- Code Version:  Develop

**Comment by dt2patel** [comment]
Correction on the issue: The micro cart height was previously set to 100vh - bottom nav height. This causes issues on iOS because viewport height his counted without browser chrome. When the browser chrome is visible, the bottom nav overlaps the checkout button in the Microcart. 

The solution is to let the micro cart be full height and overlap the bottom navigation. The user will click the back button to close the Microcart and get access to the bottom nav. 

This is also a better user experience because once a user is on a cart page they shouldn't be distracted with other buttons that may deviate them from checkout.
